name: Build and Push

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build # Replace with your build command

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"

      - name: Debug
        run: |
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Repository: ${{ github.repository }}"
          echo "GitHub Token: ${{ secrets.GH_TOKEN }}"

      - name: Commit and Push Changes
        run: |
          echo "GitHub Token: ${{API_TOKEN_GITHUB}}"
          git remote add target-repo https://github.com/dhaval15/meadow.git # Change to your new repository URL
          git push target-repo main # Change to your target branch
        env:
          API_TOKEN_GITHUB:: ${{ secrets.GH_TOKEN }}
